Update `database_cleaner-active_record`
We were getting the following error in
`spec/support/database_cleaner.rb`

```
NoMethodError:
  undefined method `schema_migration' for an instance of ActiveRecord::ConnectionAdapters::PostgreSQLAdapter
```

Upgrading `database_cleaner-active_record` fixes this issue. Given that
we appear to depend on this being up-to-date to successfully run the
test suite, I've added this as a test dependency (we have it as one in
some of our other repos)